apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: falco
  labels:
    name: falco
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  source:
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 1.10.0
    helm:
      releaseName: falco
      values: |
        falco:
          enabled: true
        falco.rules:
          enabled: true
        falco.rules.file:
          enabled: true
          path: "/etc/falco/falco.yaml"
        tty:
          enabled: true
# syncPolicy:
#   automated:
#     prune: true
#     selfHeal: true